spring: 
  datasource: 
    #数据源的基本信息
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/djz
    type: com.alibaba.druid.pool.DruidDataSource
    #配置数据源的其他设置
    initalSize: 5
    minldle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRuns: 60000
    minEvictableldleTimeMillis: 300000
    restOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true 
    
    
 